#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CommercialLiteFinal.Droid.Resource", IsApplication=true)]

namespace CommercialLiteFinal.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::CommercialLiteFinal.Droid.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::CommercialLiteFinal.Droid.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::CommercialLiteFinal.Droid.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060004
			public const int accent = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int background = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int borderColor = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int dark = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int main = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int secondary = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int text = 2131099651;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int barcode = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_bg_squared = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int circle_edit = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int edit = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int edittext_bg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int history = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int list = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int locked = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int login_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int logo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int logo_nome = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int logo_nome_branco = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int logout = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090050
			public const int add_produto = 2131296336;
			
			// aapt resource value: 0x7f090046
			public const int adicionar_produto = 2131296326;
			
			// aapt resource value: 0x7f09003e
			public const int btnAddCliente = 2131296318;
			
			// aapt resource value: 0x7f090031
			public const int btnAddItem = 2131296305;
			
			// aapt resource value: 0x7f090021
			public const int btnDecrement = 2131296289;
			
			// aapt resource value: 0x7f090044
			public const int btnDesbloquear = 2131296324;
			
			// aapt resource value: 0x7f090041
			public const int btnFinalizar = 2131296321;
			
			// aapt resource value: 0x7f090023
			public const int btnIncrement = 2131296291;
			
			// aapt resource value: 0x7f090037
			public const int btnLogin = 2131296311;
			
			// aapt resource value: 0x7f090010
			public const int btnNovo = 2131296272;
			
			// aapt resource value: 0x7f090024
			public const int btnPrices = 2131296292;
			
			// aapt resource value: 0x7f090012
			public const int btnSair = 2131296274;
			
			// aapt resource value: 0x7f090011
			public const int btnSalvos = 2131296273;
			
			// aapt resource value: 0x7f09003c
			public const int btnVerItens = 2131296316;
			
			// aapt resource value: 0x7f090045
			public const int contentFrame = 2131296325;
			
			// aapt resource value: 0x7f090028
			public const int descontos = 2131296296;
			
			// aapt resource value: 0x7f09004d
			public const int home = 2131296333;
			
			// aapt resource value: 0x7f09000f
			public const int imageView1 = 2131296271;
			
			// aapt resource value: 0x7f09000b
			public const int lblCliente = 2131296267;
			
			// aapt resource value: 0x7f090002
			public const int lblCodigo = 2131296258;
			
			// aapt resource value: 0x7f09000a
			public const int lblData = 2131296266;
			
			// aapt resource value: 0x7f090026
			public const int lblDataPreco = 2131296294;
			
			// aapt resource value: 0x7f09002f
			public const int lblDesconto = 2131296303;
			
			// aapt resource value: 0x7f090004
			public const int lblDoc = 2131296260;
			
			// aapt resource value: 0x7f09001b
			public const int lblEAN = 2131296283;
			
			// aapt resource value: 0x7f09003d
			public const int lblEndereco = 2131296317;
			
			// aapt resource value: 0x7f09000d
			public const int lblInfo = 2131296269;
			
			// aapt resource value: 0x7f09003b
			public const int lblItens = 2131296315;
			
			// aapt resource value: 0x7f09003a
			public const int lblLoja = 2131296314;
			
			// aapt resource value: 0x7f090003
			public const int lblNome = 2131296259;
			
			// aapt resource value: 0x7f090039
			public const int lblOrcamento = 2131296313;
			
			// aapt resource value: 0x7f090033
			public const int lblPreco = 2131296307;
			
			// aapt resource value: 0x7f090032
			public const int lblQtd = 2131296306;
			
			// aapt resource value: 0x7f09001d
			public const int lblQtdEstoque = 2131296285;
			
			// aapt resource value: 0x7f09000c
			public const int lblTotal = 2131296268;
			
			// aapt resource value: 0x7f09001c
			public const int lblUnidade = 2131296284;
			
			// aapt resource value: 0x7f090025
			public const int lblValor = 2131296293;
			
			// aapt resource value: 0x7f09001f
			public const int lblValorTotal = 2131296287;
			
			// aapt resource value: 0x7f090014
			public const int lblVendedor = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int lblVersao = 2131296277;
			
			// aapt resource value: 0x7f090038
			public const int linear0 = 2131296312;
			
			// aapt resource value: 0x7f090000
			public const int linearLayout1 = 2131296256;
			
			// aapt resource value: 0x7f090029
			public const int linearLayout10 = 2131296297;
			
			// aapt resource value: 0x7f09002c
			public const int linearLayout11 = 2131296300;
			
			// aapt resource value: 0x7f09003f
			public const int linearLayout12 = 2131296319;
			
			// aapt resource value: 0x7f090007
			public const int linearLayout2 = 2131296263;
			
			// aapt resource value: 0x7f09001e
			public const int linearLayout3 = 2131296286;
			
			// aapt resource value: 0x7f090001
			public const int linearLayout4 = 2131296257;
			
			// aapt resource value: 0x7f090020
			public const int linearLayout5 = 2131296288;
			
			// aapt resource value: 0x7f090017
			public const int linearLayout6 = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int linearLayout7 = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int linearLayout8 = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int linearLayout9 = 2131296282;
			
			// aapt resource value: 0x7f090009
			public const int listaClientes = 2131296265;
			
			// aapt resource value: 0x7f09000e
			public const int listaExportados = 2131296270;
			
			// aapt resource value: 0x7f090042
			public const int listaItens = 2131296322;
			
			// aapt resource value: 0x7f090043
			public const int listaProdutos = 2131296323;
			
			// aapt resource value: 0x7f090034
			public const int logo = 2131296308;
			
			// aapt resource value: 0x7f090051
			public const int logout = 2131296337;
			
			// aapt resource value: 0x7f090049
			public const int menu_exportar1 = 2131296329;
			
			// aapt resource value: 0x7f09004c
			public const int menu_exportar2 = 2131296332;
			
			// aapt resource value: 0x7f09004a
			public const int menu_logout = 2131296330;
			
			// aapt resource value: 0x7f090048
			public const int menu_novo1 = 2131296328;
			
			// aapt resource value: 0x7f09004b
			public const int menu_novo2 = 2131296331;
			
			// aapt resource value: 0x7f09004e
			public const int novo_pedido = 2131296334;
			
			// aapt resource value: 0x7f090013
			public const int relativeLayout1 = 2131296275;
			
			// aapt resource value: 0x7f090047
			public const int remover_produto = 2131296327;
			
			// aapt resource value: 0x7f09004f
			public const int salvar_pedido = 2131296335;
			
			// aapt resource value: 0x7f090052
			public const int scan = 2131296338;
			
			// aapt resource value: 0x7f090016
			public const int scrollView1 = 2131296278;
			
			// aapt resource value: 0x7f090008
			public const int searchView = 2131296264;
			
			// aapt resource value: 0x7f090006
			public const int textView1 = 2131296262;
			
			// aapt resource value: 0x7f090027
			public const int textView2 = 2131296295;
			
			// aapt resource value: 0x7f090030
			public const int textView3 = 2131296304;
			
			// aapt resource value: 0x7f09002b
			public const int textView4 = 2131296299;
			
			// aapt resource value: 0x7f09002e
			public const int textView5 = 2131296302;
			
			// aapt resource value: 0x7f090005
			public const int toolbar = 2131296261;
			
			// aapt resource value: 0x7f09002a
			public const int txtAliquota = 2131296298;
			
			// aapt resource value: 0x7f090040
			public const int txtObs = 2131296320;
			
			// aapt resource value: 0x7f090036
			public const int txtPassword = 2131296310;
			
			// aapt resource value: 0x7f090022
			public const int txtQuantidade = 2131296290;
			
			// aapt resource value: 0x7f090035
			public const int txtUsername = 2131296309;
			
			// aapt resource value: 0x7f09002d
			public const int txtVlDesc = 2131296301;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int customer_list_row_item = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int CustomerSearch = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int export_list_row_item = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ExportList = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Home = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Item = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int item_list_row_item = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int Login = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Main = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int Order = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int OrderItems = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int product_list_row_item = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int ProductSearch = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int Unlock = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int zxingscanneractivitylayout = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int zxingscannerfragmentlayout = 2130968591;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int item_options_menu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int options_menu = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int order_options_menu = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int product_search_options_menu = 2131230723;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05000b
			public const int add = 2131034123;
			
			// aapt resource value: 0x7f050017
			public const int add_customer = 2131034135;
			
			// aapt resource value: 0x7f05001a
			public const int add_payment = 2131034138;
			
			// aapt resource value: 0x7f050014
			public const int add_product = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int add_to_order = 2131034133;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f05001f
			public const int apply_discount = 2131034143;
			
			// aapt resource value: 0x7f050006
			public const int customer_search_placeholder = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int customer_search_title = 2131034119;
			
			// aapt resource value: 0x7f05001b
			public const int discount = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int discount_al = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int discount_hint = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public const int discount_vl = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int export = 2131034144;
			
			// aapt resource value: 0x7f050008
			public const int export_list_title = 2131034120;
			
			// aapt resource value: 0x7f050021
			public const int finalize = 2131034145;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int home = 2131034114;
			
			// aapt resource value: 0x7f050025
			public const int locked_device = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int locked_message = 2131034150;
			
			// aapt resource value: 0x7f050022
			public const int login = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int logout = 2131034147;
			
			// aapt resource value: 0x7f050011
			public const int new_ = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int new_order = 2131034130;
			
			// aapt resource value: 0x7f050019
			public const int notes = 2131034137;
			
			// aapt resource value: 0x7f05000f
			public const int order = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int order_items = 2131034128;
			
			// aapt resource value: 0x7f050005
			public const int product_search_placeholder = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int product_search_title = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int product_title = 2131034115;
			
			// aapt resource value: 0x7f05000e
			public const int remove = 2131034126;
			
			// aapt resource value: 0x7f050018
			public const int remove_customer = 2131034136;
			
			// aapt resource value: 0x7f050013
			public const int save = 2131034131;
			
			// aapt resource value: 0x7f05000a
			public const int scan = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int search = 2131034121;
			
			// aapt resource value: 0x7f050024
			public const int unlock_device = 2131034148;
			
			// aapt resource value: 0x7f05000c
			public const int view = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int view_all = 2131034125;
			
			// aapt resource value: 0x7f050028
			public const int view_orders = 2131034152;
			
			// aapt resource value: 0x7f050027
			public const int view_prices = 2131034151;
			
			// aapt resource value: 0x7f050016
			public const int view_products = 2131034134;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070005
			public const int Button_Light = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int Button_Primary = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int Spinner_Primary = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int Tema_Commercial = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Tema_Commercial_Escuro = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int Text_Primary = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int Text_White = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
